S2C-1/contact-section
SSNT1/2AFarm-client pull request #1
Opened 2023-11-13 14:12 UTC by AlexNicolici

https://artech-dev.atlassian.net/browse/S2C-1

2023-11-13 14:16 UTC, Dumnezeu1 requested changes

2023-11-13 14:16 UTC, Dumnezeu1 commented on public/index.html
> +<script src="https://kit.fontawesome.com/634efea5da.js" crossorigin="anonymous"></script>
Ce e asta?

2023-11-13 14:16 UTC, Dumnezeu1 commented on src/components/Contact.js
> +              <span className="font-semibold">RO16TREZ2915069XXX011364</span>
Astea hardcodate ar trebuie puse intr-un config.js sau ceva

2023-11-13 14:16 UTC, Dumnezeu1 commented on src/components/Contact.js
> +      </div>
Asta  ar trebui pusa intr-un component diferit care accepta src, title, height,etc la props

2023-11-13 14:23 UTC, AlexNicolici commented on public/index.html
> +<script src="https://kit.fontawesome.com/634efea5da.js" crossorigin="anonymous"></script>
Iconitele din sectiunea de Contact

2023-11-15 09:27 UTC, AlexNicolici commented on src/components/Contact.js
> +      </div>
done

2023-11-15 09:28 UTC, Dumnezeu1 approved these changes

2023-11-15 09:28 UTC, merged